sudo: required

services:
 - docker

script:
  - go get github.com/dghubble/sling
  - make cross
  - make static
  - cp mquery mquery-linux-amd64

  # Update docker for multi-stage build
  - sudo service docker stop
  - curl -fsSL https://get.docker.com/ | sudo sh

  # Build all images
  - docker build --build-arg PLATFORM=linux-amd64 -t mplatform/mquery:linux-amd64 -f packaging/Dockerfile.linux .
  - docker build --build-arg PLATFORM=linux-arm -t mplatform/mquery:linux-arm -f packaging/Dockerfile.linux .
  - docker build --build-arg PLATFORM=linux-arm64 -t mplatform/mquery:linux-arm64 -f packaging/Dockerfile.linux .
  - docker build --build-arg PLATFORM=linux-ppc64le -t mplatform/mquery:linux-ppc64le -f packaging/Dockerfile.linux .
  - docker build --build-arg PLATFORM=linux-s390x -t mplatform/mquery:linux-s390x -f packaging/Dockerfile.linux .

  # Test at least Intel image
  - docker run mplatform/mquery:linux-amd64 golang

  - >
    if [ -n "$TRAVIS_TAG" ]; then
      # Push all images
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

      docker tag mplatform/mquery:linux-amd64 mplatform/mquery:${TRAVIS_TAG}-linux-amd64
      docker tag mplatform/mquery:linux-arm mplatform/mquery:${TRAVIS_TAG}-linux-arm
      docker tag mplatform/mquery:linux-arm64 mplatform/mquery:${TRAVIS_TAG}-linux-arm64
      docker tag mplatform/mquery:linux-ppc64le mplatform/mquery:${TRAVIS_TAG}-linux-ppc64le
      docker tag mplatform/mquery:linux-s390x mplatform/mquery:${TRAVIS_TAG}-linux-s390x

      # push version for each platform
      docker push mplatform/mquery:${TRAVIS_TAG}-linux-amd64
      docker push mplatform/mquery:${TRAVIS_TAG}-linux-arm
      docker push mplatform/mquery:${TRAVIS_TAG}-linux-arm64
      docker push mplatform/mquery:${TRAVIS_TAG}-linux-ppc64le
      docker push mplatform/mquery:${TRAVIS_TAG}-linux-s390x

      # Download manifest-tool
      wget https://github.com/estesp/manifest-tool/releases/download/v0.6.0/manifest-tool-linux-amd64
      mv manifest-tool-linux-amd64 manifest-tool
      chmod +x manifest-tool

      # Push manifest-list
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 --template "mplatform/mquery:${TRAVIS_TAG}-OS-ARCH" --target "mplatform/mquery:$TRAVIS_TAG"
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 --template "mplatform/mquery:${TRAVIS_TAG}-OS-ARCH" --target "mplatform/mquery:latest"
    fi
