version: 1.0.{build}
image: Visual Studio 2017

build_script:
  - go get github.com/dghubble/sling
  - go build mquery.go
  - docker build -t mplatform/mquery:windows-amd64 -f packaging/Dockerfile.windows .

test_script:
  - docker run mplatform/mquery:windows-amd64 golang

deploy_script:
  - ps: >-
      if (Test-Path Env:\APPVEYOR_REPO_TAG_NAME) {

        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

        docker tag mplatform/mquery:windows-amd64 mplatform/mquery:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64

        docker push mplatform/mquery:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64

      }
